### ISSUE TITLE
Repo unification

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#515]
We should sooner rather than later unify `gem` and `ocs3`. I want to make a list of issues to solve and then we can go ahead and do it. the builds are very similar so it should be more or less straightforward I think

I suppose it is up for discussion whether to unite them but if we do we need to solve:

- [x] Make gem use the same versioning schema
- [x] use the same package style #514 
- [x] Decide a direction `gem` into `ocs3` or viceversa
- [x] Check how to keep the history
- [x] Review that deployment is still possible for gem and seqexec
- [x] Unify travis
- [ ] Unify README, (ocs3 is mostly obsolete)
- [x] Wiki?

Feel free to add issues I may have forgotten

**Comment by cquiroz** [comment]
I'll start with my opinion. I'd rather have all the code in one repo rather than in N, the ITAC experience shows how hard is to keep things in sync when they are in different repos.

Also given the `seqexec` is already in a production state I'd like `gem` to be folded in `ocs3` rather than the other way around. I don't want to mess too much with our build, especially with the building the distributions (though we may migrate to docker at some stage)

**Comment by jdnavarro** [comment]
Another alternative, which I'd slightly prefer, to a single monorepo is having both `gem` and the `seqexec` as [`git submodules`](https://git-scm.com/docs/git-submodule) on a very minimal parent repo called `ocs3`, or perhaps, have `gem` as a submodule on the `seqexec` repo since it seems the `seqexec` will depend on `gem` and not the other way around.

The CLI to the `submodule` git subcommand used to be quite quirky, you might have seen some serious ranting on them 😆 , but it's improved drastically in latest git releases. The main advantage of the submodule approach is that both repos would keep being independent while making sure they can be built together at every commit.

I haven't seen any popular Scala project using git submodules though, so I'm suspecting there may be some gotchas with sbt or something I'm not seeing.

Preserving the history when merging 2 repos is relatively straightforward as long as there are no path clashes between them or if there are it's clear one file should be picked over the other.

The gist of it can be seen on this [blog post](https://thoughts.t37.net/merging-2-different-git-repositories-without-losing-your-history-de7a06bba804), but there are many descriptions of the same pattern when googling it.

**Comment by swalker2m** [comment]
At least in the old OCS world, I advocated keeping all the applications in one big build along with the underlying science program model.  It's far more convenient when the model changes because you can see everything that it impacts immediately and you're forced to deal with it.

How much time will this add to the build though?  I'm starting to wonder if that'll be practical given how much time scala.js adds. If the Travis build time is indicative, a clean build will take roughly 4x what it takes now for the `gem` project alone:

![travis-build-time](https://user-images.githubusercontent.com/4906023/39576535-d900ac50-4eb4-11e8-92ce-afeead3ed207.jpeg)

The OT will be bigger than the seqexec presumably and then there's the TCC, etc.

I don't know what the seqexec schedule is.  What's the driver for doing this now?  Is the idea to start using the new sequence model now?  I think @tpolecat convinced me that we should have an API layer for obtaining the model instead of directly using the DAOs.  My understanding was that we'd be working on the amnesty list until June though.

I know @cquiroz has been steadily adopting settings and practices from the gem build in the seqexec. What are the remaining differences?

**Comment by cquiroz** [comment]
@jdnavarro I suspect the issue with submodules is `sbt`. To be workable you'd need an sbt build at each submodule and at the top level which is probably much harder than it sounds. I tried to do something like that at the ocs3 level and failed, possibly due to my lack of understanding of `sbt` or due to some of its inherent limitations.
i know that you can't just import build A and build B to create a superset of both

**Comment by cquiroz** [comment]
@swalker2m  `ocs3` build takes around 19 min. The drivers for this:

* Start using the new model soon, possibly with GHOST or at the latest NIRi which puts it in a July/august timeframe
* Keep them evolving together

I listed as check items the issues I think we have to deal with, there maybe more I don't recall. but I don't see any fundamental reason they couldn't be together. As you mentioned I've tried to keep all/most of the build settings from gem in ocs3

**Comment by cquiroz** [comment]
I think using `aggregates` we could make top level projects, e.g. `odb`, `ot`, `seqexec` to make it easier for developers but it would fail in travis if you forget to update the other projects. `gem` already does that by putting `coreJS` out of the `gem` aggregate

**Comment by tpolecat** [comment]
I think the monorepo (or not) question may depend on our deployment strategy. If we're deploying the whole universe every time (odb, ot, seqexec, qpt, tcc, etc.) then a monorepo makes sense. If we're deploying bits and pieces independently then we will need an internal versioning scheme for protocols and so on, at which point distinct repos might help from a discipline standpoint. It seems to me that we should just deploy everything every time and avoid these integration problems.

**Comment by cquiroz** [comment]
This can be closed
