### ISSUE TITLE
Sequences should have meaningful urls

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/ocs3#52]
URLs can be used to navigate directly to a given sequence/step

**Comment by jdnavarro** [comment]
Related to #50, this issue may include the functionality to update the URL as it scrolls to a given sequence. This would allow saving an URL for the position for things like URL sharing or bookmarking and would prevent losing the position on a refresh event.

I'm aware in plain react this is usually done with something like [`react-router`](https://github.com/reactjs/react-router) but there may be a solution a baked in `diode` since this is a frequent use case.

**Comment by cquiroz** [comment]
`scala-js-react` has support for a router
